let skip_defaults_vim=1

" standard stuff

set number
"set relativenumber
set nocompatible
"set ruler
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2
set smartindent
set smarttab
set autoindent
set formatoptions=qrn1
"set cursorline
set nobackup
set noswapfile
set backspace=indent,eol,start
set nowritebackup
set laststatus=0
set icon
set nohlsearch
set noincsearch
set noshowmatch
set linebreak

" system clipboard (+) support need to install vim-gtk3
set clipboard=unnamedplus

" source $PWD/.vimrc securely
set exrc
set secure

" column stuff if needed
" set colorcolumn=110
" highlight ColorColumn ctermbg=darkgrey

" fixes 'Press ENTER or type command to continue'
set shortmess=a
set cmdheight=1

syntax enable
filetype plugin on

" memory management

set hidden
set history=100

" solarized

set background=dark
let g:solarized_termcolors=256
let g:solarized_termtrans=1
colorscheme solarized

" start at last place you were editing

au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif