" designed for vim 8+. for more info and faq see:
"    https://gitlab.com/skilstak/config/vim

let skip_defaults_vim=1

" standard stuff

set number
"set relativenumber
set nocompatible
"set ruler
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2
set smartindent
set smarttab
set autoindent
set formatoptions=qrn1
"set cursorline
set nobackup
set noswapfile
set backspace=indent,eol,start
set nowritebackup
set laststatus=0
set icon
set nohlsearch
set noincsearch
set noshowmatch
set linebreak

" system clipboard (+) support need to install vim-gtk3
set clipboard=unnamedplus

" source $PWD/.vimrc securely
set exrc
set secure

" column stuff if needed
" set colorcolumn=110
" highlight ColorColumn ctermbg=darkgrey

" fixes 'Press ENTER or type command to continue'
set shortmess=a
set cmdheight=1

syntax enable
filetype plugin on

" memory management

set hidden
set history=100

" plugins

call plug#begin('~/.vim/plugged')
Plug 'altercation/vim-colors-solarized'
Plug 'vim-pandoc/vim-pandoc'
Plug 'vim-pandoc/vim-pandoc-syntax'
Plug 'skilstak/vim-abnf-utf8'
call plug#end()

" solarized

set background=dark
"let g:solarized_visibility="high"
"let g:solarized_contrast="high"
let g:solarized_termcolors=16
"let g:solarized_termtrans=1
colorscheme solarized

" markdown.pandoc

let g:pandoc#modules#disabled = ["folding"]
"let g:pandoc#syntax#conceal#use = 0
let g:pandoc#syntax#conceal#urls = 1
let g:pandoc#syntax#conceal#blacklist = ["atx","codeblock_start","codeblock_delim"]
au syntax * hi link pandocAtxStart Type 
au syntax * hi link pandocAtxHeader Type
au syntax * hi Default cterm=none term=none
au syntax * hi pandocEmphasis cterm=none term=none ctermfg=Magenta 
au syntax * hi pandocStrong cterm=bold term=bold ctermfg=Magenta 
au syntax * hi pandocStrongEmphasis cterm=none term=none ctermfg=Red
au syntax * hi link pandocDelimitedCodeBlock pandocNoFormatted
au syntax * hi SpellBad ctermfg=White ctermbg=Red cterm=none

" syntax helpers

au bufnewfile,bufRead *.crontab set ft=crontab
au bufnewfile,bufRead *ssh/config set filetype=sshconfig
au bufnewfile,bufRead *gitconfig set filetype=gitconfig
au bufnewfile,bufread /tmp/psql.edit.* set syntax=sql

" type-specific 

autocmd Filetype go setlocal ts=6 sw=6 sts=0 expandtab

" displays all the syntax rules for current position

function! <SID>SynStack()
	if !exists("*synstack")
		return
	endif
  echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
endfunc  

" start at last place you were editing

au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" pane switching

map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

" Go stuff (I really don't care for fatih/vim-go)
autocmd vimleavepre *.go !gofmt -w %

" Commands
command JQ %!jq .
